OLFG-184: Call the token endpoint on the backend
hmrc/centralised-authorisation-test-frontend pull request #4
Opened 2022-11-14 09:16 UTC by steve-edmans

Call the token endpoint on the backend passing in the details entered by the user.

Description of changes:

---
### PR Author Checklist
#### Before creating PR
- [ ] Have you met all the acceptance criteria from the ticket?
- [ ] Have you added good quality tests to evidence this?
- [ ] Have you run all the unit and integration tests?
- [ ] Have you checked that combined code coverage is at 100%?
- [ ] Have you checked there aren’t any build warnings?
- [ ] Have you checked all dependencies are up-to-date? [Catalogue](https://catalogue.tax.service.gov.uk/repositories?name=centr&team=One+Login+For+Government&repoType=Service)
- [ ] Have you updated external test packs (ui and performance) to fix any tests broken by your changes and/or added tests for new functionality?
- [ ] Have you tested your changes using the latest versions of other required microservices?
- [ ] Have you considered any required changes to app-config-{base/env} repos?
- [ ] Have you checked the pipeline is healthy? (last pipeline run passed in [Jenkins](https://build.tax.service.gov.uk/job/Centralised%20Authorisation/), other changes to this service not currently 'In Pipeline' on Jira)

#### After PR has been raised
- [ ] Have you checked the PR Builder passes?
- [ ] Have you moved the ticket to ‘Ready for Review’ in Jira?
- [ ] Have you notified the team this is ready to review?

### PR Reviewer Checklist
#### Before Reviewing
- [ ] Have you assigned yourself to the ticket in Jira?
- [ ] Have you moved the ticket to 'In Review'?
- [ ] Have you read through the ticket to understand what functionality is required by this change?

#### Whilst Reviewing
- [ ] Have you checked the changes meet the acceptance criteria from the ticket and has appropriate tests to evidence this?
- [ ] Have you checked coding style and naming conventions are consistent with our other services?
- [ ] Have you discussed any questions you have with the PR Author?
- [ ] Have you run all the unit and integration tests?
- [ ] Have you checked that combined code coverage is at 100%?
- [ ] Have you checked there aren’t any build warnings?
- [ ] Have you checked all dependencies are up-to-date? [Catalogue](https://catalogue.tax.service.gov.uk/repositories?name=centr&team=One+Login+For+Government&repoType=Service)
- [ ] Have you run the UI tests locally? (with changes and latest versions of other apps)
- [ ] Have you run a PT smoke test locally? (with changes and latest versions of other apps)
- [ ] Have any required changes to app-config-{base/env} repos been raised as separate PR(s)?
- [ ] Have you checked the pipeline is healthy? (last pipeline run passed in [Jenkins](https://build.tax.service.gov.uk/job/Centralised%20Authorisation/), other changes to this service not currently 'In Pipeline' on Jira)

2022-11-14 15:35 UTC, peteanning requested changes
Could you also add some text to the README with a URL that resolves to the test page.

2022-11-14 15:35 UTC, peteanning commented on test/uk/gov/hmrc/centralisedauthorisationtestfrontend/model/GNAPTokenSpec.scala
> +class GNAPTokenSpec extends AnyWordSpec with Matchers {
It would be good to have a test for the sessionValue function to document behaviour?

and for the behaviour on the appy method dropping the GNAP scheme.

2022-11-14 15:40 UTC, steve-edmans commented on app/uk/gov/hmrc/centralisedauthorisationtestfrontend/controllers/HelloWorldController.scala
> -class HelloWorldController @Inject()(
It is deleted.

2022-11-15 10:17 UTC, peteanning approved these changes

2022-11-15 10:21 UTC, merged